The following example code shows an example of try-catch:

try {

>FileInputStream fis = new FileInputStream(\"test.txt\");

} catch (FileNotFoundException e) {

>e.printStackTrace();

}

From Java 7 onwards, you can also catch multiple exceptions in a single
catch block, as shown in the following example. It's useful when you
have the same code in all the catch blocks.

public static void foo(int x) throws IllegalArgumentException,
NullPointerException {

>// some code

}

public static void main(String\[\] args) {

>try {

>>foo(10);

>} catch (IllegalArgumentException \| NullPointerException e) {

>>System.out.println(e.getMessage());

>}

}